
on:
  push:
    branches: [main]
  workflow_dispatch:

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true   # <-- Fixes ragg/pkgdown issues

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Add mrc-ide R-universe
        run: |
          echo "options(repos = c(
            mrcide='https://mrc-ide.r-universe.dev',
            CRAN='https://cloud.r-project.org'
          ))" >> ~/.Rprofile

      - name: Install dependencies
        run: |
          options(repos = c(
            mrcide='https://mrc-ide.r-universe.dev',
            CRAN='https://cloud.r-project.org'
          ))
          install.packages(c(
            "pkgdown",
            "odin2",
            "dust2",
            "monty",
            "scales",
            "ggplot2"
          ))
        shell: Rscript {0}

      - name: Install your package
        run: |
          R CMD INSTALL .
        shell: bash

      - name: Build pkgdown
        run: pkgdown::build_site()
        shell: Rscript {0}

      - name: Deploy ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: docs
