
on:
  push:
    branches: [main]
  workflow_dispatch:

name: pkgdown

jobs:
  pkgdown:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    env:
      RSPM: https://packagemanager.rstudio.com/all/__linux__/focal/latest
      # Add mrc-ide r-universe
      R_UNIVERSE: https://mrc-ide.r-universe.dev

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install dependencies (including odin2, dust2, monty)
        run: |
          options(repos = c(
            mrcide = 'https://mrc-ide.r-universe.dev',
            CRAN   = 'https://cloud.r-project.org'
          ))
          install.packages(c(
            "odin2",
            "dust2",
            "monty",
            "pkgdown"
          ))
          install.packages("local::.", repos = c(
            mrcide = 'https://mrc-ide.r-universe.dev',
            CRAN   = 'https://cloud.r-project.org'
          ))
        shell: Rscript {0}

      - name: Build pkgdown site
        run: pkgdown::build_site()
        shell: Rscript {0}

      - name: Deploy to GitHub Pages ðŸš€
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: docs
